name: Sidekick Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      ASPNETCORE_ENVIRONMENT: Production
    steps:
    - name: Git - Checkout
      uses: actions/checkout@v2
    - name: .NET - Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: NuGet - Setup
      uses: NuGet/setup-nuget@v1.0.5
    - name: NuGet - Source
      uses: fabriciomurta/ensure-nuget-source@v1
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Tests
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
    - name: Tests - Unit Tests Report
      uses: dorny/test-reporter@v1.3.1
      with:
        name: Tests - Unit Tests
        path: '**/*.trx'
        reporter: dotnet-trx
        
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.7
      with:
        reports: ' tests\Sidekick.Application.Tests\coverage.cobertura.xml' # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
        targetdir: 'coveragereport' # REQUIRED # The directory where the generated report should be saved.
        reporttypes: 'HtmlInline;Cobertura' # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
        verbosity: 'Info' # The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off
        title: 'Sidekick Coverage' # Optional title.
        tag: '${{ github.run_number }}_${{ github.run_id }}' # Optional tag or build version.

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CoverageReport # Artifact name        
        path: coveragereport # Directory containing files to upload
