name: Electron Release

on:
  push:
    branches:
    - 2.x
  workflow_dispatch:

jobs:
  electron-release:
    runs-on: windows-latest
    steps:
    - name: Git - Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: GitVersion - Install
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: GitVersion - Execute
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with:
        useConfigFile: true
        additionalArguments: '/updateprojectfiles'

    - name: Environment - Build Number
      uses: myci-actions/export-env-var@1
      with:
        name: BUILD_NUMBER
        value: ${{ steps.gitversion.outputs.fullSemVer }}

    - name: Environment - Github Token
      uses: myci-actions/export-env-var@1
      with:
        name: GITHUB_TOKEN
        value: ${{ github.token }}

    - name: .NET 6 - Setup (Required for Electron)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: .NET 7 - Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: .NET - Restore
      run: dotnet restore

    - name: .NET - Build
      run: dotnet build --no-restore

    - name: .NET - Tests
      run: dotnet test --no-build --verbosity normal

    - name: .NET - Tool Restore
      run: |
        cd ./src/Sidekick.Electron
        dotnet tool restore

    - name: Electron - Build
      run: |
        cd ./src/Sidekick.Electron
        dotnet tool install ElectronNET.CLI -g --version 23.6.1
        electronize build /target win /PublishSingleFile false

    - name: Artifact - Build
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Sidekick-windows
        path: ./src/Sidekick.Electron/bin/Desktop/Sidekick-Setup.exe

    - name: Main Release - Notes
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        name: 'Release v${{ steps.gitversion.outputs.majorMinorPatch }}'
        tag: 'v${{ steps.gitversion.outputs.majorMinorPatch }}'
        version: 'v${{ steps.gitversion.outputs.majorMinorPatch }}'
        publish: false
        prerelease: false

    - name: Main Release - Asset
      if: github.ref == 'refs/heads/main'
      uses: xresloader/upload-to-github-release@v1.3.4
      with:
        file: src/Sidekick.Electron/bin/Desktop/Sidekick-Setup.exe
        tag_name: 'v${{ steps.gitversion.outputs.majorMinorPatch }}'
        draft: true
        verbose: true
        overwrite: true
