name: Test new flow

on:
  workflow_dispatch:

jobs:
  wpf-release:
    runs-on: windows-latest

    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Version
        id: version
        shell: pwsh
        run: |
          # Get the current date
          $DATE = Get-Date -Format "yyyy.M.d"
   
          # Get the current time
          $NOW = Get-Date
   
          # Calculate the seconds since midnight
          $MIDNIGHT = $NOW.Date
          $SECONDS = ($NOW - $MIDNIGHT).TotalSeconds -as [int]
   
          # Construct the version using DATE and SECONDS
          $VERSION = "$DATE.$SECONDS"
          Write-Output "Generated version: $VERSION"
   
          # Export version as an output
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT

      - name: Version - Update project files
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: "src/**/*.csproj"
          version: ${{ steps.version.outputs.version }}

      - name: Release - Notes
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: 'Release v${{ steps.version.outputs.version }}'
          tag: 'v${{ steps.version.outputs.version }}'
          version: 'v${{ steps.version.outputs.version }}'
          publish: false
          prerelease: false

      - name: Release - Asset
        uses: xresloader/upload-to-github-release@v1.3.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          file: 'download-instructions.txt'
          tag_name: 'v${{ steps.version.outputs.version }}'
          draft: true
          verbose: true
          overwrite: true
