name: Release Notes

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  release-notes:
    runs-on: windows-latest
    steps:
    - name: Git - Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: GitVersion - Install
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: GitVersion - Execute
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with:
        useConfigFile: true
        additionalArguments: '/updateprojectfiles'

    - name: Main Release - Notes
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        name: 'Release v${{ steps.gitversion.outputs.majorMinorPatch }}'
        tag: 'v${{ steps.gitversion.outputs.majorMinorPatch }}'
        version: 'v${{ steps.gitversion.outputs.majorMinorPatch }}'
        publish: false
        prerelease: false
