name: Velopack Beta

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  wpf-beta:
    runs-on: windows-latest

    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Version
        id: version
        run: |
          # Get the current date
          $DATE = Get-Date -Format "yyyy.M.d"

          # Get the current time in hours and minutes (24-hour format)
          $TIME = Get-Date -Format "Hmm"

          # Construct the version using DATE and TIME
          $VERSION = "$DATE.$TIME"
          Write-Output "Generated version: $VERSION"

          # Export version as an output
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT

      - name: Version - Update project files
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: "src/**/*.csproj"
          version: ${{ steps.version.outputs.version }}

      - name: Environment - Build Number
        uses: myci-actions/export-env-var@1
        with:
          name: BUILD_NUMBER
          value: ${{ steps.version.outputs.version }}

      - name: Environment - Github Token
        uses: myci-actions/export-env-var@1
        with:
          name: GITHUB_TOKEN
          value: ${{ github.token }}

      - name: .NET - Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: .NET - Restore
        run: dotnet restore

      - name: .NET - Build
        run: dotnet build --no-restore

      - name: .NET - Tests
        run: dotnet test --no-build --verbosity normal

      - name: Build - Sidekick.Protocol
        run: dotnet publish src/Sidekick.Protocol/Sidekick.Protocol.csproj -p:PublishProfile=Build

      - name: Build - Sidekick.Wpf
        shell: pwsh
        run: |
          $version = "${{ steps.version.outputs.version }}"
          Write-Output "Version: $version"

          dotnet tool update -g vpk
          dotnet publish src/Sidekick.Wpf/Sidekick.Wpf.csproj -c Release --self-contained -r win-x64 -o .\velopack-publish
          vpk pack -u Sidekick -v $version -p .\velopack-publish -e Sidekick.exe

      - name: Git - Setup
        run: |
          git config --global url."https://user:${{ secrets.GITHUB_TOKEN }}@github".insteadOf https://github
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Git - Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_VELOPACK }}

      - name: Git - Push to repository
        shell: pwsh
        run: |
          $deployRepository = "git@github.com:Sidekick-Poe/Sidekick-Velopack.git"
          Write-Output "Deploy repository: $deployRepository"

          # Clone `gh-pages` branch.
          git clone $deployRepository -b gh-pages --single-branch "dist"

          Push-Location "dist"
          try {
              Write-Output "Removing previous files..."
              if (Test-Path "Application Files") {
                  Remove-Item -Path "Application Files" -Recurse
              }
              if (Test-Path "Sidekick.application") {
                  Remove-Item -Path "Sidekick.application"
              }

              Write-Output "Copying new files..."
              Copy-Item -Path "../velopack-publish" -Destination . -Recurse

              # Stage and commit.
              git add -A
              git commit -m "Update to v$version"
              git push
          } finally {
              Pop-Location
          }
